name: pages-Workflow
on: 
  push:
      branches:
         - main
  pull_request:
      branches:
        - main

jobs:
  build:
   runs-on: self-hosted
   steps:
      - name: Run shell cmd
        run: |
          echo "Hello world"
          npm -v
          
     
    
